#! /usr/bin/env ruby

# New Relic plugin to monitor FareHarbor booking rate.

require "rubygems"
require "bundler/setup"
require "newrelic_plugin"
require "pg"

module BookingRateAgent

  class Agent < NewRelic::Plugin::Agent::Base

    agent_guid "com.fareharbor.booking_rate"
    agent_version "1.0.1"
    agent_config_options :pg_host, :pg_port, :pg_database, :pg_username, :pg_password, :environment, :metrics
    agent_human_labels("Booking Rate Agent") { "#{environment}" }

    def poll_cycle
      connection = PGconn.open(:host => pg_host, :port => pg_port, :dbname => pg_database, :user => pg_username, :password => pg_password)

      for metric in metrics do
        metric_total = 0
        response = connection.exec(metric['query'])

        # This assumes the query uses 1 aggregate and groups by 0 or 1 values.
        if response.nfields == 1
          metric_total = response.getvalue(0, 0)
        else
          for i in 0..response.ntuples
            aggregate_value = response.getvalue(i, 0)
            group = response.getvalue(i, 1)
            metric_total += aggregate_value
            report_metric "BookingRate/#{metric['name']}_#{group}", "Value", aggregate_value
          end
        end

        report_metric "BookingRate/#{metric['name']}_total", "Value", metric_total
      end

      connection.close()
    end

  end

  # Register this agent with the component.
  NewRelic::Plugin::Setup.install_agent :booking_rate, BookingRateAgent

  # Launch the agent; this never returns.
  NewRelic::Plugin::Run.setup_and_run

end
