newrelic:
  license_key: 'YOUR_LICENSE_KEY_HERE'
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  # verbose: 1

# Agent Configuration:
agents:
  booking_rate:
    environment: 'development'
    pg_host: '127.0.0.1'
    pg_port: 5432
    pg_database: 'db'
    pg_username: 'admin'
    pg_password: '********'
