newrelic:
  license_key: 'YOUR_LICENSE_KEY_HERE'
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  # verbose: 1

# Agent Configuration:
agents:
  booking_rate:
    environment: 'development'
    databases:
      replica:
        host: '127.0.0.1'
        port: 5432
        database: 'db'
        username: 'admin'
        password: '********'
    metrics:
      - name: "Example query"
        database: replica  # "replica" by default
        query: "SELECT COUNT(*), type FROM example_table GROUP BY type"
